FROM alpine:3.14 as BUILDER
RUN apk update && apk add --no-cache \
        git \
        bash \
        libc6-compat
WORKDIR /opt/build
COPY ./obsutil.tar.gz ./obsutil.tar.gz
RUN tar -xf ./obsutil.tar.gz

# real service
FROM python:3.9.13

WORKDIR /usr/src/app

COPY ./run.sh ./run.sh
COPY ./requirements.txt ./requirements.txt
COPY ./aimTrace.py ./aimTrace.py
COPY ./obsHandler.py ./obsHandler.py

COPY --from=BUILDER /opt/build/obsutil /usr/src/app/obsutil

RUN pip install --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple pip
RUN pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

ENTRYPOINT ["/usr/src/app/run.sh"]
